### ISSUE TITLE
Add and index file and a start script for express projects

### ISSUE THREAD

**Issue by EmilIvanov** [MentorMate/node-project-cli#51]
# Description
Given an `express` project with `typescript` is being generated, we want to be able to start the resulting application.

# Tasks
- [ ] add `src/index.ts` which creates and starts an express app
- [ ] add a `start` script to `package.json`
- [ ] add the following middleware:
  - [helmet](https://www.npmjs.com/package/helmet)
  - [cors](https://www.npmjs.com/package/cors)
  - [compression](https://www.npmjs.com/package/compression)
- [ ] register a `Hello World!` handler at `GET /`
- [ ] print a clickable URL after the app has stated for ease of navigation
