### ISSUE TITLE
Add dotenv support

### ISSUE THREAD

**Issue by EmilIvanov** [MentorMate/node-project-cli#52]
# Description
We want our generated projects to have some `.env` support for ease of providing environment variables

# Tasks
- [x] add the [dotenv](https://www.npmjs.com/package/dotenv) package under `devDependencies`
- [x] add a `.env.example` file with `PORT=3000`
- [x] update the `start` script ti [preload](https://github.com/motdotla/dotenv#preload) `.env`
- [x] update the `image:run` script to [specify](https://docs.docker.com/engine/reference/commandline/run/#env) the `.env` file
