### ISSUE TITLE
Implement global error handing for express apps

### ISSUE THREAD

**Issue by EmilIvanov** [MentorMate/node-project-cli#55]
# Description
Given an express project with typescript is being generated, the resulting application should handle errors thrown by handlers.

# Tasks
- [x] Research HTTP Exceptions libraries and pick one. ([http-errors](https://www.npmjs.com/package/http-errors), [boom](https://www.npmjs.com/package/@hapi/boom))
- [x] Update the example express app to throw HTTP Exceptions 
- [x] Implement (or use existing) middleware that:
  - converts HTTP exceptions into their corresponding responses
  - converts uncaught exceptions into a 500 response and log the original error
