### ISSUE TITLE
Add validation for express apps

### ISSUE THREAD

**Issue by EmilIvanov** [MentorMate/node-project-cli#56]
# Description
Given an express project with typescript is being generated, the resulting application should validate its inputs and output.

# Tasks
- [x] setup [zod](https://www.npmjs.com/package/zod)
- [x] create middleware for validating requests with zod schemas
- [x] validate environment configuration on startup
