### ISSUE TITLE
Add logging for express apps

### ISSUE THREAD

**Issue by EmilIvanov** [MentorMate/node-project-cli#57]
# Description
Given an express project with typescript is being generated, the resulting application should provide a logger to its handlers and middleware.

# Tasks
- [x] add [pino](https://www.npmjs.com/package/pino)
- [x] add an example request logger
- [x] overwrite the error handler to log using this logger
