### ISSUE TITLE
Setup a PostgreSQL database for express apps

### ISSUE THREAD

**Issue by EmilIvanov** [MentorMate/node-project-cli#58]
# Description
The CLI should provide an option for setting up a PostgreSQL database

# Tasks
- [x] add a database option to the CLI
- [x] add PostgreSQL variables to `.env.example`
- [x] add a `docker-compose.yml` file that will spin up a PostgreSQL 13 server using the environment variables in `.env`
